---
- name: Load SSH keys from public_keys.yml
  include_vars: public_keys.yml
- name: Create users group
  group:
    name=users
    state=present

- name: Create user accounts
  user:
    name={{ item.user }}
    shell=/bin/bash
    groups=users
  with_items: account_names

- name: Authorize everyoene's SSH keys 
  authorized_key:
    user={{ item.user }}
    key={{ item.key }}
    state=present
 with_items: account_names
