---
language: python
python: "2.7"
sudo: false

install:
    - pip install ansible

script:
    - "ansible-playbook -i tests/inventory provision_bastion.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision_buildmaster.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision_proxy.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision_playground.yaml --syntax-check" 
