---
language: python
python: "2.7"
sudo: false

install:
    - pip install ansible

script:
    - "ansible-playbook -i tests/inventory provision/bastion.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision/buildmaster.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision/proxy.yaml --syntax-check" 
    - "ansible-playbook -i tests/inventory provision/playground.yaml --syntax-check" 
