---
language: python
python: "2.7"
sudo: false

install:
    - pip install ansible

before_script: 
    - ansible-galaxy install -r galaxy_roles.yaml -p roles/

script:
    - "ansible-playbook -i tests/inventory site.yaml --syntax-check" 
