---
# This playbook applies all roles to their respective hosts
- include: provision/bastion.yaml
- include: provision/playground.yaml
- include: provision/buildmaster.yaml
- include: provision/proxy.yaml
- include: provision/ndk.yaml

