---
# This playbook applies all roles to their respective hosts
- include: provision_bastion.yaml
- include: provision_playground.yaml
- include: provision_buildmaster.yaml
- include: provision_proxy.yaml
- include: provision_macs.yaml

