---
- name: See whether we can skip the slow git clone later
  stat: path="{{rust_checkout_path}}/README.md"
  register: rust_checkout_stat

- name: Git clone Rust
  git:
    repo=https://github.com/rust-lang/rust.git
    dest={{rust_checkout_path}}
    accept_hostkey=yes
    force=yes
  become: yes
  become_method: sudo
  when: rust_checkout_stat.stat.exists == False

- name: Ensure the ansible_ssh_user has perms on the Rust checkout
  file: 
    path={{ rust_checkout_path }}
    owner={{ ansible_ssh_user }}
    recurse=yes
  become: yes
  become_method: sudo

- include: linux.yaml
  when: ansible_os_family == "Debian"

- include: osx.yaml
  when: ansible_os_family == "Darwin"

- name: make clean
  command: 'make clean'
  args:
      chdir: "{{ rust_checkout_path }}"

- name: "make -j{{ rust_make_threads }} rustc-stage2"
  command: 'make -j{{ rust_make_threads }} rustc-stage2 VERBOSE=1'
  args:
      chdir: "{{ rust_checkout_path }}"

- name: make dist
  command: 'make dist'
  args:
      chdir: "{{ rust_checkout_path }}"

