--- 

android_sdk_path: /opt/android/sdk
android_ndk_path: /opt/android/ndk/android-ndk-r10e
ndk_standalone_path: /opt/android

rust_checkout_path: /opt/rustlang

# make's -j option 
rust_make_threads: 2


rust_compile_dependencies:
  - "gcc-4.7"
  - "g++-4.7"
  - "make"
  - "curl"
  - "git"
  - "gcc-multilib"
  - "g++-multilib"
