---
- name: apt-get update
  apt:
      update_cache=yes
- name: Install prerequisite packages
  apt:
      pkg={{ item }}
      state=present
  with_items: 
      - python
      - python-pip
      - python-dev
      - python-setuptools
      - stunnel
      # we need Git later and Ansible doesn't auto-install it
      - git
- name: install Buildbot
  easy_install:
      name: buildbot==0.8.12
- name: Create buildbot user
  user:
      name: "buildbot"
      home: "/home/buildbot"
      shell: /bin/bash
      createhome: yes  
- name: Clone the Buildbot configs
  git: 
      repo='https://github.com/rust-lang/rust-buildbot.git'
      dest='/home/buildbot/rust-buildbot'

- name: Start Buildbot
  command: buildbot start master
  args:
      chdir: /home/buildbot/rust-buildbot/master
